run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters-settings:
  gofmt:
    simplify: true

linters:
  enable:
    - govet
    - golint
    - gofmt
    - gosec
    - gocritic
    - goimports
    - deadcode
    - gocyclo
  disable:
    - errcheck
    - staticcheck

issues:
  exclude-rules:
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"
    - linters:
        - golint
      text: "should have comment or be unexported"
